# ModcraftForge configuration file
# if need specific options, please create issue on github https://github.com/modcraftmc/ModcraftForge/issues

# Allow to modify display of logs
removeDataFixerlogs=false
showDimensionLogs=false

# Allow to modify custom tablist options
enableCustomTablist=false

# custom message for tablist, you can use '/n' to create new line. color are supported
customHeader="DEFAULT HEADER"
customFooter="DEFAULT FOOTER"

# Tab refresh rate in tick (20tick = 1 second)
tabRefreshRate=20